#!/bin/bash

source /morningstar/python/env/bin/activate

# BASE_DIR=/home/lithium/newfo
# MDB=msgstore.db
# KEY=whatsapp.cryptkey
# WA=wa.db
STAMP=`date +%Y-%m-%d_%H-%M-%S`
# EXPORT_DIR=/home/lithium/export/$STAMP

# mkdir $STAMP

python __main__.py \
    -a \
    --time-offset=11 \
    --size=0 \
    $@
#    |& tee logfile-$STAMP.log

#    -m ./WhatsApp \
#    -o /home/lithium/export/$STAMP \
#    -b $BASE_DIR/$MDB \
#    -w $BASE_DIR/$WA \
#    --time-offset=10 \
#    $@
