#!/bin/bash

source /morningstar/python/env/bin/activate

BASE_DIR=/mnt/local/renata/Services/WhatsApp
DATA_DIR="$BASE_DIR/Media/Databases"
MDB="$DATA_DIR/msgstore.db"
KEY=whatsapp.cryptkey
WA="$DATA_DIR/wa.db"
STAMP=`date +%Y-%m-%d_%H-%M-%S`
EXPORT_DIR="$BASE_DIR/Exported"

echo Base directory: $BASE_DIR
echo Data directory: $DATA_DIR
echo Message database: $MDB
echo Contacts database:  $WA
echo Export directory: $EXPORT_DIR

# read -r -p "Are you sure? [y/N]" -n 1
# echo # (optional) move to a new line
# case "$REPLY" in
#   y|Y ) echo "Operation continues";;
#   * ) echo "Operation is cancelled"; exit 1;
# esac

python __main__.py \
    -a \
    --time-offset=10 \
    --size=0 \
    -d $MDB \
    -w $WA \
    -o $EXPORT_DIR
    $@

#    -m ./WhatsApp \
#    -o /home/lithium/export/$STAMP \
ls

#find "$EXPORT_DIR"/ -name "*.html" -type f -mmin +120 -delete


